language: 
  - node_js
node_js:
  - "8"
env:
  - TEST_DATABASE_URL=mongodb://localhost/testdb
  - CODECOV_TOKEN=d8f74d39-238a-4566-97c9-d0873ef83c36
install:
  - npm install
  - npm install -g codecov
script:
  - npm run test
  - codecov
services:
  - mongodb
before_script:
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
notifications:
  - email: false
